baseURL = "https://miscellonomicon.netlify.com/"
languageCode = "en"
defaultContentLanguage = "zh-cn"                            # en / zh-cn / ... (This field determines which i18n file to use)
title = "Miscellonomicon"
theme = "apollo"
paginate = 5                                                # Number of articles per page
enableEmoji = true
preserveTaxonomyNames = true
hasCJKLanguage = true     # has chinese/japanese/korean ?
# googleAnalytics = ""      # UA-XXXXXXXX-X
footnotereturnlinkcontents = "↩"

[permalinks]
  post = "/:year/:month/:filename/"

[author]                                                    # essential
  name = "Chuanyi"

# Menu configs
[[menu.main]]             # config your menu              # 配置目录
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
# [[menu.main]]
#   name = "Archives"
#   weight = 20
#   identifier = "archives"
#   url = "/post/"
# [[menu.main]]
#   name = "Tags"
#   weight = 30
#   identifier = "tags"
#   url = "/tags/"
# [[menu.main]]
#   name = "Categories"
#   weight = 40
#   identifier = "categories"
#   url = "/categories/"
# [[menu.main]]
#   name = "Homepage"
#   weght = 50
#   identifier = "homepage"
#   url = "/homepage.html"

[Languages]
  [Languages.zh-cn]
  title = "杂学宝典"
  weight = 1
  languagename = "汉语"

    [[Languages.zh-cn.menu.main]]
    name = "首页"
    weight = 1

    [[Languages.zh-cn.menu.main]]
      url = "/about/"
      name = "关于"
      weight = 0

    [[Languages.zh-cn.menu.main]]
      name = "存档"
      weight = 2
      identifier = "archives"
      url = "/post/"

    [[Languages.zh-cn.menu.main]]
    name = "标签"
    weight = 3
    identifier = "tags"
    url = "/tags/"

  [Languages.en]
  title = "Miscellonomicon"
  weight = 0
  languagename = "English"

    [[Languages.en.menu.main]]
    url = "/"
    name = "Home"
    weight = 1

    [[Languages.en.menu.main]]
    url = "/about/"
    name = "About"
    weight = 0

    [[Languages.en.menu.main]]
    name = "Archives"
    weight = 2
    identifier = "archives"
    url = "/post/"

    [[Languages.en.menu.main]]
    name = "Tags"
    weight = 3
    identifier = "tags"
    url = "/tags/"

[taxonomies]
  tag = "tags"
  category = "categories"

[blackfriday]
smartypants = false

